# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo "tasks - init"
    before: |
      echo "tasks - init - before"
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update -y && sudo apt-get install -y terraform jq
    command: |
      echo "tasks - init - command"
      #echo $VOLTERRA_CORP_STAGING_P12 |base64 -d > volterra-corp.staging.api-creds.p12
      #echo $PUBLIC_SERVER_CA |base64 -d | zcat > public_server_ca.crt

    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
