# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo "tasks - init"
    before: |
      echo "tasks - init - before"
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update -y -q && sudo apt-get install -y terraform jq
      wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
      tar zxf openshift-install-linux.tar.gz openshift-install
      sudo mv openshift-install /usr/local/bin/ && rm openshift-install-linux.tar.gz
      wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
      tar zxf openshift-install-linux.tar.gz oc kubectl
      sudo mv oc kubectl /usr/local/bin/ && rm openshift-client-linux.tar.gz
      curl -L https://github.com/derailed/k9s/releases/download/v0.25.8/k9s_Linux_x86_64.tar.gz | sudo tar -C /usr/local/bin -xvz k9s
      
    command: |
      echo "tasks - init - command"

    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
